<?php
/**
 * Combo Deal Product view template
 *
 * @see Arvato_ComboDeals_Block_Combodeals
 */
?>
<?php
/** @var Mage_Core_Helper_Data $coreHelper */
$coreHelper = $this->helper('core');
$countTimers = 0;
$parentId = null;
$selectionIds = array();
?>
<div class="combo-deals">
    <h3><?php echo $this->__(Mage::helper('combodeals')->getHeaderTitle()) ?></h3>
    <?php foreach ($this->getOptions() as $option): ?>
        <?php $productPlus = ""; ?>
        <?php $parentId = $option->getParentId(); ?>
        <div class="combodeal-pageHolder">
            <div class="combodeal-page-title">
                <h3><?php echo $this->escapeHtml($option->getName()); ?></h3>
            </div>
            <div class="combodeal-page-timer">
                <?php if (Mage::helper('combodeals/timer')->isEnableModuleOutput()): ?>
                    <?php $countTimers +=1; ?>
                    <?php echo $this->getDealTimerHtml($option, $countTimers) ?>
                <?php endif; ?>
            </div>
            <div class="combodeal-page-instock">
                <div class="stock-box">
                    <?php if (in_array('fewleft', $this->getDealStockStatus($option))): ?>
                        <span></span>
                        <span class="few"></span>
                        <span></span>
                        <p class="few"><?php echo $this->__('few left') ?></p>
                    <?php elseif (in_array('instock', $this->getDealStockStatus($option))): ?>
                        <span class="in"></span>
                        <span></span>
                        <span></span>
                        <p class="in"><?php echo $this->__('in stock') ?></p>
                    <?php else: ?>
                        <span></span>
                        <span></span>
                        <span class="out"></span>
                        <p class="out"><?php echo $this->__('out of stock') ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <!-- Included Products -->
            <?php
            if ($option->getSelections()):
                /** @var Mage_Catalog_Model_Product $selection */
                ?>
                <?php
                foreach ($option->getSelections() as $selection):
                    $selectionIds[] = $selection->getSelectionId();
                    $selection->setData('url', null);
                    $selection->setData('request_path', null);
                    ?>
                    <div class="span3">
                        <a href="<?php echo $selection->getUrlModel()->getUrl($selection, array('_nosid' => true, '_ignore_category' => true)) ?>" class="product <?php echo $productPlus ?>" title="<?php echo $this->escapeHtml($selection->getName()) ?>">
                            <div class="image">
                                <img src="<?php echo $this->helper('catalog/image')->init($selection, 'small_image')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($selection->getName()) ?>" />
                            </div>
                            <div class="info">
                                <strong>
                                    <?php echo $this->escapeHtml($selection->getName()) ?>
                                </strong>
                                <?php echo $this->getDealPriceHtml($selection, $option, false, '-new') ?>
                            </div>
                        </a>
                    </div>
                    <?php $productPlus = "plus" ?>
                <?php endforeach; ?>
                <div class="span3">
                    <div class="result">
                        <div class="total"><?php echo $this->__('Total') ?> <small><?php echo $coreHelper->currency($this->getTotalPrice($option), true, false) ?></small></div>
                        <div class="price"><?php echo $coreHelper->currency($this->getTotalDiscountedPrice($option), true, false) ?></div>
                        <?php if (in_array('fewleft', $this->getDealStockStatus($option)) || in_array('instock', $this->getDealStockStatus($option))): ?>
                            <a class="btn btn-primary btn-small" href="<?php echo $this->getComboDealAddToCartUrl($parentId, $option->getId(), $selectionIds) ?>" title="<?php echo $this->__('Order all') ?>"><?php echo $this->__('Order all') ?></a>
                            <?php unset($selectionIds);?>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
