<?php
/**
 * Combo Deal Product listing template
 *
 * @see Arvato_ComboDeals_Block_Combodeals
 */
?>
<?php
/** @var Mage_Core_Helper_Data $coreHelper */
$coreHelper = $this->helper('core');
$countTimers = 0;
$parentId = null;
$selectionIds = array();
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $optionsCollection = $this->getCollection(); ?>

<div class="page-header">
    <div class="row-fluid">
        <div class="span8 mobile-50 first-in-row-mobile">
            <h1 class="headline-normal"><?php echo $this->__("Combo Deals") ?></h1>
        </div>
        <div class="span4 mobile-50">
            <p class="results">
            </p>
        </div>
    </div>
</div>
<?php echo $this->getToolbarHtml(); ?>
<?php if ($optionsCollection->getSize()): ?>
    <div class="combo-deals">
        <?php
        foreach ($optionsCollection->getItems() as $_option) :
            $optionIds[] = $_option->getOptionId();
        endforeach;
        ?>
        <?php foreach ($this->getOptions($optionIds) as $option): ?>
            <?php $productPlus = ''; ?>
            <?php $parentId = $option->getParentId(); ?>
            <div class="combodeal-pageHolder">
                <div class="combodeal-page-title">
                    <h3><?php echo $this->escapeHtml($option->getName()); ?></h3>
                </div>
                <div class="combodeal-page-timer">
                    <?php if (Mage::helper('combodeals/timer')->isEnableModuleOutput()): ?>
                        <?php $countTimers +=1; ?>
                        <?php echo $this->getDealTimerHtml($option, $countTimers) ?>
                    <?php endif; ?>
                </div>
                <div class="combodeal-page-instock">
                    <div class="stock-box">
                        <?php if (in_array('out_of_stock', Mage::helper('combodeals')->getDealStockStatus($option))): ?>
                            <span></span>
                            <span class="out"></span>
                            <span></span>
                            <p class="out"><?php echo $this->__('out of stock') ?></p>
                        <?php elseif (in_array('few_left', Mage::helper('combodeals')->getDealStockStatus($option))): ?>
                            <span></span>
                            <span></span>
                            <span class="few"></span>
                            <p class="few"><?php echo $this->__('few left') ?></p>
                        <?php elseif (in_array('in_stock', Mage::helper('combodeals')->getDealStockStatus($option))): ?>
                            <span class="in"></span>
                            <span></span>
                            <span></span>
                            <p class="in"><?php echo Mage::helper('combodeals')->__('in stock') ?></p>
                        <?php endif; ?>        
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <!-- Included Products -->
                <?php
                if ($option->getSelections()):
                    /** @var Mage_Catalog_Model_Product $selection */
                    ?>
                    <?php
                    foreach ($option->getSelections() as $selection):
                        $selectionIds[] = $selection->getSelectionId();
                        $selection->setData('url', null);
                        $selection->setData('request_path', null);
                        ?>
                        <div class="span3">
                            <a href="<?php echo $selection->getUrlModel()->getUrl($selection, array('_nosid' => true, '_ignore_category' => true)) ?>" class="product <?php echo $productPlus ?>" title="<?php echo $this->escapeHtml($selection->getName()) ?>">
                                <div class="image">
                                    <img src="<?php echo $this->helper('catalog/image')->init($selection, 'small_image')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($selection->getName()) ?>" />
                                </div>
                                <div class="info">
                                    <strong>
                                        <?php echo $this->escapeHtml($selection->getName()) ?>
                                    </strong>
                                    <?php echo $this->getDealPriceHtml($selection, $option, false, '-new') ?>
                                </div>
                            </a>
                        </div>
                        <?php $productPlus = 'plus'; ?>
                    <?php endforeach; ?>
                    <div class="span3">
                        <div class="result">
                            <div class="total"><?php echo $this->__('Total') ?> <small><?php echo $coreHelper->currency($this->getTotalPrice($option), true, false) ?></small></div>
                            <div class="price"><?php echo $coreHelper->currency($this->getTotalDiscountedPrice($option), true, false) ?></div>
                            <?php if (in_array('few_left', $this->getDealStockStatus($option)) || in_array('in_stock', $this->getDealStockStatus($option))): ?>
                                <a class="btn btn-primary btn-small" href="<?php echo Mage::helper('combodeals')->getComboDealAddToCartUrl($parentId, $option->getId(), $selectionIds) ?>" title="<?php echo $this->__('Order all') ?>"><?php echo $this->__('Order all') ?></a>
                                <?php unset($selectionIds); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php echo $this->getToolbarHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('There are no combodeal products found.'); ?></p>
<?php endif ?>
