<?php
/**
 * Combodeals Timer
 * @category    Arvato
 * @package     Arvato_ComboDeals
 * @copyright   Copyright (c) arvato 2015
 */
?>
<?php
$option = $this->getOption();
$count = $this->getCount();
$toDate = $option->getToDate();
?>
<div id="heading<?php echo $count; ?>" style="color:#<?php //echo $head_color;  ?>; font-size: 18px; font-weight:bold;padding-top:15px;clear: both;">
    <?php echo $this->__('Deal End in'); ?>
    <div id="countbox_<?php echo $count; ?>" class="timer-view"></div>
    <div class='clear'></div>
    <div class='timerdate' id="caption<?php echo $count; ?>">
        <span class='hour' style='margin:0px'>
            <?php echo $this->__('Days') ?>
        </span>
        <span class='hour' style='margin:0 0 0 33px'>
            <?php echo $this->__('Hours') ?>
        </span>
        <span class='min'  style='margin:0 0 0 24px'>
            <?php echo $this->__('Minutes') ?>
        </span>
        <span class='sec' style='margin:0 0 0 14px'>
            <?php echo $this->__('Seconds') ?>
        </span>
    </div>
</div>
<script type="text/javascript">
    var dthen<?php echo $count; ?> = new Date("<?php echo Mage::getModel('core/date')->date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
    start = "<?php echo Mage::getModel('core/date')->date("m/d/y h:i:s A", strtotime(Mage::app()->getLocale()->date(null, null, null, true))); ?>";
    start_date = Date.parse(start);
    var dnow<?php echo $count; ?> = new Date(start_date);
    if (CountStepper > 0)
        ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
    else
        ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php echo $count; ?>));
    gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
    var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
    CountBack(gsecs<?php echo $count; ?>, "countbox_" + timer, timer);
    timer++;
</script>