<?php
/**
 * Shopping cart item render template
 * 
 * @category    Arvato
 * @package     Arvato_ComboDeals
 * @copyright   Copyright (c) arvato 2015
 */
/** @var Arvato_ComboDeals_Block_Checkout_Cart_Item_Renderer $this */
?>
<?php
$_item = $this->getItem();

if (Mage::helper('core')->isModuleEnabled('Arvato_Preorder')) {
    $preorderHelper = $this->helper('arvato_preorder/quote');
}

$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);

$_hasUrl = $this->hasProductUrl();
$displayBoth = $this->helper('tax')->displayCartBothPrices();
?>

<tr class="product">
    <td class="product-image">
        <?php if ($_hasUrl): ?>
            <a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>">
            <?php endif ?>
            <img src="<?php echo $this->getProductThumbnail()->resize(94); ?>" width="94" height="94" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>">
            <?php if ($_hasUrl): ?>
            </a>
        <?php endif ?>
    </td>
    <td class="product-description">
        <h2 class="product-title">
            <?php if ($_hasUrl): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif ?>
                <?php echo $this->escapeHtml($this->getProductName()) ?>
                <?php if ($_hasUrl): ?></a><?php endif ?>
        </h2>
        <?php if ($_options = $this->getOptionList()): ?>
            <ul class="product-options unstyled">
                <?php foreach ($_options as $_option): ?>
                    <li>
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>                        
                        <?php echo $_formatedOptionValue['value'] ?>
                        <?php if (isset($_formatedOptifonValue['full_view'])): ?>
                            <dl>
                                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                            </dl>
                        <?php endif ?>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
        <?php if ($messages = $this->getMessages()): ?>
            <?php foreach ($messages as $message): ?>
                <?php echo $message['text'] ?>
            <?php endforeach ?>
        <?php endif ?>
        <?php if (isset($preorderHelper) && $preorderHelper->isPreorderItem($_item)): ?>
            <?php echo $preorderHelper->getPreorderNotice($_item) ?>
        <?php endif; ?>
        <?php if (isset($preorderHelper) && $preorderHelper->isBackorderItem($_item)): ?>
            <?php echo $preorderHelper->getBackorderNotice($_item) ?>
        <?php endif; ?>
        <?php if ($addInfoBlock = $this->getProductAdditionalInformationBlock()): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
    </td>
    <td class="table-amount text-center">
        <label for="cart[<?php echo $_item->getId() ?>][qty]" class="table-amount-header"><?php echo $this->__('Quantity') ?></label>
        <div class="row-fluid">
            <div class="mobile-50 first-in-row-mobile">
                <?php
                    $_option_count = 9;
                ?>
                <select name="cart[<?php echo $_item->getId() ?>][qty]" class="selectpicker">
                <?php for ($i = 0; $i <= $_option_count; $i++) : ?>
                        <option value="<?php echo $i ?>"<?php if (($this->getQty() * 1) == $i) : ?> selected="selected"<?php endif; ?>><?php echo $i ?></option>
                    <?php endfor ?>
                </select>
            </div>
            <div class="mobile-50">
                <button type="submit" class="link-action" title="<?php echo $this->__('Update Shopping Cart'); ?>"><?php echo $this->__('update') ?></button>
            </div>
        </div>
    </td>
    <td class="table-price">
        <ul class="product-actions unstyled">
<?php $i = 0; ?>
            <?php if ($isVisibleProduct): ?>
                <li>
                    <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit') ?>" class="link-action product-actions-edit"><i class="icon-pencil"></i><span><?php echo $this->__('edit') ?></span></a>
                </li>
<?php endif ?>
            <li>
                <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove item') ?>" class="link-action product-actions-delete"><i class="icon-trash"></i><span><?php echo $this->__('Delete') ?></span></a>
            </li>
        </ul>
        <p class="price-box mobile-clear">
<?php if (($this->helper('tax')->displayCartPriceExclTax() || $displayBoth) && !$_item->getNoSubtotal()): ?>
                <span class="<?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>cart-tax-total<?php else: ?>cart-price<?php endif ?>">
                <?php if ($canApplyMsrp): ?>
                        --
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </span>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif ?>
            <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                <span class="<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>cart-tax-total<?php else: ?>cart-price<?php endif; ?>">
                <?php if ($canApplyMsrp): ?>
                        --
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedRowAmount()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </span>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedRowAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </p>
    </td>
</tr>
