<?php
/**
 * This template is use to show the grid container
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) arvato 2015
 */
?>
<?php
/**
 * @see Arvato_ComboDeals_Block_Adminhtml_ComboDeals
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('combodeals')->__('Combo Deal Products') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php if (!$this->isSingleStoreMode()): ?>
    <?php echo $this->getChildHtml('store_switcher'); ?>
<?php endif; ?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
