<?php

?>


<script type="text/javascript">
//<![CDATA[

var bundleTemplateBox = '<table class="border" cellpadding="0" cellspacing="0">' +
    '    <thead>' +
    '        <tr class="headings">' +
    '            <th><?php echo Mage::helper('catalog')->__('Name') ?></th>' +
    '            <th><?php echo Mage::helper('catalog')->__('Original Price') ?></th>' +
    '            <th><?php echo Mage::helper('catalog')->__('Available Quantity') ?></th>' +
    '            <th class="type-order"><?php echo Mage::helper('combodeals')->__('Discount Type') ?></th>' +
    '            <th class="type-order"><?php echo Mage::helper('combodeals')->__('Discount Amount') ?></th>' +
     '            <th class="type-order"><?php echo Mage::helper('combodeals')->__('Minimum Quantity') ?></th>' +
    '            <th class="type-order"><?php echo Mage::helper('combodeals')->__('Position') ?></th>' +
    '            <th class="last">&nbsp;</th>' +
    '        </tr>' +
    '    </thead> ' +
    '    <tbody>' +
    '    </tbody>' +
    '</table>';

var bundleTemplateRow ='<td>' +
                '    <input type="hidden" id="<?php echo $this->getFieldId() ?>_id_{{index}}" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][selection_id]" value="{{selection_id}}">' +
                '    <input type="hidden" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][option_id]" value="{{option_id}}">' +
                '    <input type="hidden" class="product" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][product_id]" value="{{product_id}}">' +
                '    <input type="hidden" class="product" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][sku]" value="{{sku}}">' +
                '    <input type="hidden" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][delete]" value="" class="delete">' +
                '    {{name}}<br />' +
                '   <div  class="nobr">' +
                '        <strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> {{sku}}' +
                '    </div>' +
                '</td>' +
                '<td><strong>{{price}}</strong></td>' +
                '<td><strong>{{qty}}</strong></td>' +
                '<td><?php echo $this->getDiscountTypeSelectHtml() ?></td>' +
                '<td><input class="input-text required-entry validate-zero-or-greater" type="text" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][discount_amount]" value="{{discount_amount}}"></td>' +
                '<td><input class="input-text required-entry validate-greater-than-zero" type="text" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][minimum_qty]" value="{{minimum_qty}}"></td>' +
                '<td><input class="input-text required-entry validate-greater-than-zero" type="text" name="<?php echo $this->getFieldName() ?>[{{parentIndex}}][{{index}}][position]" value="{{position}}"></td>' +
                '<td class="last"><span title="Delete Row"><?php echo $this->getSelectionDeleteButtonHtml() ?></span></td>';

Combodeal.Selection = Class.create();
Combodeal.Selection.prototype = {
    idLabel : '<?php echo $this->getFieldId() ?>',
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateBox : '',
    templateRow : '',
    itemsCount : 0,
    row : null,
    gridSelection : new Hash(),

    initialize : function() {
        this.templateBox = '<div class="grid tier form-list" id="' + this.idLabel + '_box_{{parentIndex}}">' + bundleTemplateBox + '</div>';

        this.templateRow = '<tr class="selection" id="' + this.idLabel + '_row_{{index}}">' + bundleTemplateRow + '</tr>';
    },

    showSearch : function(event) {
        var element = Event.findElement(event, 'div');
        var parts = element.id.split('_');

        var products = new Array();

        var inputs = $A($$('#' + element.id + ' tr.selection input.product'));
        for (i=0; i<inputs.length; i++) {
            products.push(inputs[i].value);
        }

        this.gridSelection.set(parts[2], $H({}));

        new Ajax.Updater(cdOption.idLabel + '_search_' + parts[2], '<?php echo $this->getSelectionSearchUrl() ?>', {
            method: 'post',
            parameters : {'index' : parts[2], 'products[]' : products, 'form_key': FORM_KEY},
            evalScripts : true
        });

        if (Event.element(event).tagName.toLowerCase() != 'button') {
            var button = Event.element(event).up('button');
        } else {
            var button = Event.element(event);
        }
        button.hide();
    },

    addRow : function (parentIndex, data) {

        var box = null;
        if (!(box = $(this.idLabel + '_box_' + parentIndex))) {
            this.addBox(parentIndex);
            box = $(this.idLabel + '_box_' + parentIndex);
        } else {
            box.show();
        }

        var option_type = $(cdOption.idLabel + '_' + parentIndex + '_discount_type');

        if(!data){
            var data = {};
        }

        data.index = this.itemsCount++;
        data.parentIndex = parentIndex;


        this.template = new Template(this.templateRow, this.templateSyntax);
        var tbody = $$('#' + this.idLabel + '_box_' + parentIndex + ' tbody');

        Element.insert(tbody[0], {'bottom':this.template.evaluate(data)});


        //set selected role
        if (data.role) {
            $A($(this.idLabel + '_' + parentIndex +'_'+ data.index +'_role').options).each(function(selection){
                if (selection.value==data.role)
                {
                    selection.selected = true;
                }
            });
        }

    },

    addBox : function (parentIndex) {
        var div = $(cdOption.idLabel + '_' + parentIndex)
        this.template = new Template(this.templateBox, this.templateSyntax);
        var data = {'parentIndex' : parentIndex};
        Element.insert(div, {'bottom':this.template.evaluate(data)});
    },

    remove : function(event) {
        var element = Event.findElement(event, 'tr');
        var container = Event.findElement(event, 'div');

        if (element) {
            Element.select(element, '.delete').each(function(elem){elem.value='1'});
            Element.select(element, ['input', 'select']).each(function(elem){elem.hide()});
            Element.removeClassName(element, 'selection');
            Element.hide(element);

            if (container) {
                if ($$('#' + container.id + ' tr.selection')) {
                    if (!$$('#' + container.id + ' tr.selection').length) {
                        container.hide();
                    }
                }
            }
        }
    },

    checkGroup : function(event) {
        var element = Event.element(event);
        if (element.type == 'radio') {
            var box = element.up('div');

            var inputs = $$('div#' + box.id + ' input.default');
            if (inputs) {
                for (i=0; i< inputs.length; i++) {
                    if (inputs[i].name != element.name) {
                        inputs[i].checked = false;
                    }
                }
            }
        }
    },

    productGridAddSelected : function(event) {
        var element = Event.findElement(event, 'button');
        var parts = element.id.split('_');

        $(cdOption.idLabel + '_search_' + parts[2]).innerHTML = '';
        $(cdOption.idLabel + '_' + parts[2] + '_add_button').show();

        this.gridSelection.get(parts[2]).each(
            function(pair) {
                var qty = pair.value.get('qty');
                var data = {
                    'name' : pair.value.get('name'),
                    'sku' : pair.value.get('sku'),
                    'price' : pair.value.get('price'),
                    'qty' : pair.value.get('qty'),
                    'position' : 1,
                    'product_id' : pair.key,
                    'option_id' : $(cdOption.idLabel + '_id_' + parts[2]).value
                };
                cdSelection.addRow(parts[2], data);
            }
        );
    },

    productGridRowInit : function(grid, row){
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        var inputs = $(row).getElementsByClassName('input-text');
        for (var i = 0; i < inputs.length; i++) {
            inputs[i].checkbox = checkbox;
            Event.observe(inputs[i], 'keyup', this.productGridRowInputChange.bind(this));
            Event.observe(inputs[i], 'change', this.productGridRowInputChange.bind(this));
        }
    },

    productGridCheckboxCheck : function(grid, element, checked) {
        var id = element.up('table').id.split('_')[4];
        if (element.value > 0) {
            if (element.checked) {
                var tr = element.parentNode.parentNode;
                if (!this.gridSelection.get(id)) {
                    this.gridSelection.set(id, new Hash());
                }
                this.gridSelection.get(id).set(element.value, $H({}));
                // Firefox returns weird line breaks and long empty spaces before and after the content
                // So we need to filter this
                var name = tr.select('td.name')[0].innerHTML.stripTags().stripScripts().unescapeHTML().replace(/[\n\r]+/g, ' ').replace(/\s{2,}/g, '');
                var sku = tr.select('td.sku')[0].innerHTML.stripTags().stripScripts().unescapeHTML().replace(/[\n\r]+/g, ' ').replace(/\s{2,}/g, '');
                var price = tr.select('td.price')[0].innerHTML.stripTags().stripScripts().unescapeHTML().replace(/[\n\r]+/g, ' ').replace(/\s{2,}/g, '');
                var qty = tr.select('td.qty')[0].innerHTML.stripTags().stripScripts().unescapeHTML().replace(/[\n\r]+/g, ' ').replace(/\s{2,}/g, '');
                this.gridSelection.get(id).get(element.value).set('name', name);
                this.gridSelection.get(id).get(element.value).set('sku', sku);
                this.gridSelection.get(id).get(element.value).set('price', price);
                this.gridSelection.get(id).get(element.value).set('qty', qty);
            } else {
                this.gridSelection.get(id).unset(element.value);
            }
        }
    },

    productGridRowClick : function(grid, event) {
        var trElement = Event.findElement(event, 'tr');
        var isInput = Event.element(event).tagName == 'INPUT';
        if (trElement) {
            var checkbox = Element.select(trElement, 'input');
            if (checkbox[0]) {
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                grid.setCheckboxChecked(checkbox[0], checked);
            }
        }
    },

    productGridRowInputChange : function(event) {
        var element = Event.element(event);
        if (!element.checkbox.checked) {
            return;
        }
        var id = element.up('table').id.split('_')[4];
        this.gridSelection.get(id).get(element.checkbox.value).set('qty', element.value);
    }
}

cdSelection = new Combodeal.Selection();
//]]>
</script>
