<?php
/**
 * Template for displaying combo-deal product prices within ComboDeal Template
 * @see Arvato_ComboDeal_Block_Price
 */
/** @var Arvato_ComboDeal_Block_Price $this */
?>
<?php
$productId = $this->getProduct()->getId();
$secondPriceLabel = $this->__('Regular Price:');
if ($this->isDiscountReceiver()) {
    $secondPriceLabel = $this->__('Discounted Price:');
}
?>

<div class="price-box">
    <?php if ($this->isDiscountReceiver()): ?>
        <s>
            <strong class="price"><?php echo $this->getFormattedRegularPrice() ?></strong>
        </s>
    <?php endif; ?>


    <span class="<?php if ($this->isDiscountReceiver()) : ?>sale<?php else: ?>regular-price<?php endif; ?>">
        <span class="price"><?php echo $this->getFormattedDiscountedPrice() ?></span>

    </span>
    <span class="combo-qty"><?php echo $this->__('For %s', $this->getSelectionQty()) ?></span>
</div>