<?php

?>
<script type="text/javascript">
optionTemplate = '<div id="<?php echo $this->getFieldId() ?>_{{index}}"  class="option-box"> ' +
    '<table class="option-header" cellpadding="0" cellspacing="0">' +
        '<thead>' +
            '<tr>' +
                '<th class="opt-order"><?php echo Mage::helper('combodeals')->__('From Date') ?></th>' +
                '<th>&nbsp;</th>' +
                '<th class="opt-order"><?php echo Mage::helper('combodeals')->__('To Date') ?></th>' +
                '<th>&nbsp;</th>' +
                '<th>&nbsp;</th>' +
                '<th>&nbsp;</th>' +
            '</tr>' +
        '</thead>' +
        '<tbody>' +
            '<tr>' +
                '<input type="hidden" id="<?php echo $this->getFieldId() ?>_id_{{index}}" name="<?php echo $this->getFieldName() ?>[{{index}}][option_id]" value="{{option_id}}">' +
                '<input type="hidden" name="<?php echo $this->getFieldName() ?>[{{index}}][delete]" value="" class="delete">' +
                '<td><input type="text" id="_from_date" name="<?php echo $this->getFieldName() ?>[{{index}}][from_date]" class="input-text required-entry" value="{{from_date}}" style="width:110px !important;" /></td>' +
                '<td><img title="Select From Date" id="_from_date_trig" src="<?php echo $this->getSkinUrl('images/grid-cal.gif');?>" class = "v-middle"></td>' +
                '<td><input type="text" id="_to_date" name="<?php echo $this->getFieldName() ?>[{{index}}][to_date]" class="input-text required-entry" value="{{to_date}}" style="width:110px !important;" /></td>' +
                '<td><img title="Select To Date" id="_to_date_trig" src="<?php echo $this->getSkinUrl('images/grid-cal.gif');?>" class = "v-middle"></td>' +
                '<td>&nbsp;<?php echo $this->jsQuoteEscape($this->getOptionDeleteButtonHtml()) ?></td>' +
                '<td>&nbsp;<?php echo $this->jsQuoteEscape($this->getAddSelectionButtonHtml()) ?></td>' +
            '</tr>' +
        '</tbody>' +
    '</table>' +
    '<div id="<?php echo $this->getFieldId() ?>_search_{{index}}">' +
    '</div>' +
    '<input type="hidden" id="<?php echo $this->getFieldId() ?>_validation_{{index}}" class="<?php echo Arvato_ComboDeals_Helper_Data::VALIDATION_CLASS_HAS_PRODUCTS; ?>">' +
'</div>';
</script>

<?php echo $this->getSelectionHtml() ?>

<script type="text/javascript">

function changeInputType(oldObject, oType) {
    var newObject = document.createElement('input');
    newObject.type = oType;
    if(oldObject.size) newObject.size = oldObject.size;
    if(oldObject.value) newObject.value = oldObject.value;
    if(oldObject.name) newObject.name = oldObject.name;
    if(oldObject.id) newObject.id = oldObject.id;
    if(oldObject.onclick) newObject.onclick = oldObject.onclick;
    if(oldObject.className) newObject.className = oldObject.className;
    oldObject.parentNode.replaceChild(newObject,oldObject);
    return newObject;
}

Combodeals.Option = Class.create();
Combodeals.Option.prototype = {
    idLabel : '<?php echo $this->getFieldId() ?>',
    top : '',
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : '',
    itemsCount : 0,
    initialize : function(template) {
        this.templateText = template;
        this.top = $('product_combodeals_container_top');
    },

    add : function(data) {

        if(!data){
            data = {};
            this.top = $('product_combodeals_container_top');
        }

        data.index = this.itemsCount++;

        this.template = new Template(this.templateText, this.templateSyntax);

        Element.insert(this.top, {'after':this.template.evaluate(data)});

        this.top = $(this.idLabel + '_' + data.index);

        // rebind change notifications
        varienWindowOnload(true);

        return data.index;
    },

    remove : function(event){
        var element = $(Event.findElement(event, 'div')).parentNode;
        if(element){
            Element.select(element, '.delete').each(function(elem){elem.value='1'});
            Element.select(element, ['input', 'select']).each(function(elem){elem.hide(); elem.className = '';});
            Element.hide(element);
        }
    }
}

var optionIndex = 0;
cdOption = new Combodeals.Option(optionTemplate);
//adding data to templates
<?php if ($this->getOptions()):?>
    <?php foreach ($this->getOptions() as $_option): ?>
    optionIndex = cdOption.add(<?php echo $_option->toJson() ?>);
    <?php if ($_option->getSelections()):?>
        <?php foreach ($_option->getSelections() as $_selection): ?>
            <?php $_selection->setName($this->escapeHtml($_selection->getName())); ?>
            cdSelection.addRow(optionIndex, <?php echo $_selection->toJson() ?>);
        <?php endforeach; ?>
    <?php endif; ?>
    <?php endforeach; ?>
    setCalendar();
<?php else: ?>
    cdOption.add();
    setCalendar();
<?php endif; ?>

function setCalendar() {
    //<![CDATA[
        Calendar.setup({
            inputField: "_from_date",
            ifFormat: "%m/%e/%Y",
            showsTime: false,
            button: "_from_date_trig",
            align: "Bl",
            singleClick : true
        });
        Calendar.setup({
            inputField: "_to_date",
            ifFormat: "%m/%e/%Y",
            showsTime: false,
            button: "_to_date_trig",
            align: "Bl",
            singleClick : true
        });
    //]]>
}
</script>